[features]
seeds = false
skip-lint = false
[programs.localnet]
space_wrapper = "F67MeXhizyw49YoN3XNMTXzjpRoRSh7Q98NYqyBXzA3r"

[programs.devnet]
space_wrapper = "F67MeXhizyw49YoN3XNMTXzjpRoRSh7Q98NYqyBXzA3r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
